### ISSUE TITLE
Android plugin 3.0.0 + Gradle 4.1 support

### ISSUE THREAD

**Issue by NinjaRat84** [boxheed/gradle-pater-build-plugin#10]
Will there be any update for newer gradle versions soon?

**Great plugin btw! :)**

Best regards

**Comment by boxheed** [comment]
@NinjaRat84 I use the latest version of this plugin elsewhere with gradle 4.3.1 but have never used it with the Android Plugin, is there something that's not working? If so an example build script that demonstrates this would be good.

**Comment by boxheed** [comment]
@NinjaRat84 I use the latest version of this plugin elsewhere with gradle 4.3.1 but have never used it with the Android Plugin, is there something that's not working? If so an example build script that demonstrates this would be good.

**Comment by boxheed** [comment]
@NinjaRat84 last call, any update otherwise I will close this issue.

**Comment by NinjaRat84** [comment]
@boxheed Got it working as expected now, this one can be closed 👍
